### ISSUE TITLE
arrow button to switch to next page isn't visible

### ISSUE THREAD

**Issue by Mallikarjunople** [devscollab/skill-board#28]
Arrow button to switch from login page/landing page is not visible properly. Fix needed..
![WhatsApp Image 2020-08-25 at 11 45 13 PM](https://user-images.githubusercontent.com/45136568/91211936-2a73d400-e72d-11ea-9bbc-f8ee68915df5.jpeg)

**Comment by tejasmorkar** [comment]
This issue is mainly because we don't have a horizontally wide design for the purple part. We've asked for a wide design so that the arrow can be shown properly in the center and on the purple design. 

Once the image is ready, we can align the arrow accordingly. 

Keep an eye on this issue for the same.

**Comment by Mallikarjunople** [comment]
okay
